version: '3.9'
services:
  db-designer:
    build:
      dockerfile: Dockerfile
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - .:/workspace:cached
      - ~/.gitconfig:/etc/gitconfig
      - ~/.ssh:/root/.ssh
