version: '3.9'
services:
  dev-portal:
    image: gingersociety/vite-react-dev:latest
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - .:/workspace:cached
      - ~/.gitconfig:/etc/gitconfig
      - ~/.ssh:/root/.ssh
