lang = "TS"
package_type = "static"

[[links]]
icon = "FaLink"
internal = true
label = "Open"
link = "https://dev-portal-staging.gingersociety.org"

[[links]]
icon = "FaCodeBranch"
internal = true
label = "Pull Requests"
link = "https://github.com/ginger-society/metadata-service-backend/pulls"

[[links]]
icon = "FaRegPlayCircle"
internal = true
label = "Pipelines"
link = "https://github.com/ginger-society/metadata-service-backend/actions"

[[links]]
icon = "FaGithub"
internal = true
label = "Browse Repo"
link = "https://github.com/ginger-society/metadata-service-backend"
