[version]
channel = "Nightly"
major = 0
minor = 12
patch = 0
revision = 0

[[references]]
file_name = "package.json"
output_type = "String"
variable = "version"

[[references]]
file_name = "src/shared/version.json"
output_type = "String"
variable = "version"

[settings]
git_url_prefix = "https://github.com/ginger-society/dev-portal-frontend"
