dir = "src/services"
lang = "TS"
organization_id = "ginger-society"
refs_file = "src/shared/references.ts"
service_type = "Portal"

[services."@ginger-society/NotificationService"]
dev = "http://localhost:3030"
stage = "https://api-staging.gingersociety.org"
stage_k8 = "http://notification-service-service"

[services."@ginger-society/IAMService"]
dev = "http://localhost:8080/iam"
stage = "https://api-staging.gingersociety.org/iam"
stage_k8 = "http://iam-service-api-service/iam"

[services."@ginger-society/MetadataService"]
dev = "http://localhost:8081/metadata"
stage = "https://api-staging.gingersociety.org/metadata"
stage_k8 = "http://metadata-service-api-service/metadata"

[portals_refs."@ginger-society/iam-frontend-users"]
dev = "http://localhost:3001"
stage = "https://iam-staging.gingersociety.org"

[ws_refs."@ginger-society/NotificationService"]
dev = "wss://api-staging.gingersociety.org/notification"
stage = "wss://api-staging.gingersociety.org/notification"
stage_k8 = "ws://notification-service-service/notification"

[urls]
dev = "http://localhost:3000"
prod = "http://localhost:8081"
stage = "https://dev-portal-staging.gingersociety.org"

[urls_ws]
