dir = "src/services"
lang = "TS"
organization_id = "ginger-society"
refs_file = "src/shared/references.ts"
service_type = "Portal"

[services."@ginger-society/MetadataService"]
prod = "https://api.gingersociety.org/metadata"
stage = "https://api.gingersociety.org/metadata"

[services."@ginger-society/IAMService"]
prod = "https://api.gingersociety.org/iam"
prod_k8 = "http://iam-service-api-service/iam"
stage = "https://api.gingersociety.org/iam"
stage_k8 = "http://iam-service-api-service/iam"

[services."@ginger-society/NotificationService"]
prod = "https://api.gingersociety.org"
stage = "https://api-staging.gingersociety.org"

[services."@ginger-society/GingerKubeService"]
prod = "https://api.gingersociety.org/kube"
stage = "https://api.gingersociety.org/kube"

[portals_refs."@ginger-society/iam-frontend-users"]
prod = "https://iam.gingersociety.org"
stage = "https://iam.gingersociety.org"

[ws_refs."@ginger-society/NotificationService"]
prod = "wss://api.gingersociety.org/notification"
stage = "wss://api.gingersociety.org/notification"

[ws_refs."@ginger-society/IAMService"]
prod = ""
prod_k8 = ""
stage = ""
stage_k8 = ""

[ws_refs."@ginger-society/GingerKubeService"]
prod = ""
stage = ""

[ws_refs."@ginger-society/MetadataService"]
prod = ""

[urls]
dev = "http://localhost:3000"
prod = "https://dev-portal.gingersociety.org"
stage = "https://dev-portal-staging.gingersociety.org"

[urls_ws]

[portal_config]
allow_registration = true
auth_redirection_path = "/#/handle-auth/"
disabled = false
friendly_name = "Dev Portal"
has_web_interface = true
id = "dev-portal-staging"
logo_url = "https://www.gingersociety.org/img/ginger-dev-portal-icon.png"
tnc_url = "https://www.gingersociety.org/terms-of-use/"
