lang = "TS"
dir = "src/services"
portal_refs_file = "src/shared/references.ts"
service_type = "Portal"

[services.IAMService]
stage_k8 = "http://iam-service-api-service/iam"
stage = "https://api-staging.gingersociety.org/iam"

[services.MetadataService]
stage = "https://api-staging.gingersociety.org/metadata"
stage_k8 = "http://metadata-service-api-service/metadata"

[portals_refs."@ginger-society/iam-frontend-users"]
stage = "https://iam-staging.gingersociety.org"
dev = "http://localhost:3001"

[urls]
stage = "https://dev-portal-staging.gingersociety.org"
dev = "http://localhost:3000"
prod = "http://localhost:8081"
