name: Build and Push Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install ginger-apps
        run: bash -c "$(curl -fsSL https://raw.githubusercontent.com/ginger-society/infra-as-code-repo/main/rust-helpers/install-pipeline-clis.sh)"

      - name: Authenticate with ginger-auth
        id: ginger-auth
        run: ginger-auth token-login ${{ secrets.GINGER_TOKEN }}

      - name: Update pipeline to running
        run: ginger-connector update-pipeline stage running

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
      - name: Report failure if Docker login fails
        if: failure()
        run: ginger-connector update-pipeline stage failed

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/dev-portal-prod-fe:latest \
            -f Dockerfile.build \
            --build-arg GINGER_TOKEN=${{ secrets.GINGER_TOKEN }} \
            --build-arg AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            --build-arg AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            --build-arg AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }} \
            --build-arg DISTRIBUTION_ID=${{ secrets.DISTRIBUTION_ID }} .
      - name: Report failure if Docker build fails
        if: failure()
        run: ginger-connector update-pipeline stage failed

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/dev-portal-prod-fe:latest
      - name: Report failure if Docker push fails
        if: failure()
        run: ginger-connector update-pipeline stage failed

      - name: Publish stage using ginger-connector
        run: ginger-connector publish stage
        env:
          GINGER_TOKEN: ${{ secrets.GINGER_TOKEN }}
      - name: Report failure if publish stage fails
        if: failure()
        run: ginger-connector update-pipeline stage failed

      - name: Update pipeline to passing
        if: success()
        run: ginger-connector update-pipeline stage passing
