name: CI
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  test:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: yarn install
      - name: Test package
        run: yarn test
      - name: Test lint
        run: yarn lint
      - name: Build package
        run: yarn build
      
